Repository cylc/cylc-ui, pull requests merged in 2019-08, with the labels that each got.

#149 Update landing page / dashboard
  src/components/core/Drawer.vue
  src/views/Dashboard.vue
Labels: enhancement

#168 task: add isHeld attribute
  src/components/cylc/Task.vue
Labels: enhancement

#188 Task failed
  src/components/cylc/Task.vue
Labels: Design

#196 Remove unused functions in Dashboard.vue
  src/views/Dashboard.vue
Labels: bug

#199 Fix toolbar displaying logic
  src/components/core/Toolbar.vue
  src/components/cylc/Toolbar.vue
  src/router/index.js
Labels: bug

#206 Fix security vulnerabilities after GitHub alert
  package-lock.json
Labels: bug

#200 Handle unknown statuses (custom icon, and console error log)
  src/components/cylc/Task.vue
Labels: enhancement

#177 Fix e2e tests
  package-lock.json
  package.json
  tests/e2e/plugins/index.js
  tests/e2e/specs/dashboard.js
  tests/e2e/specs/graph.js
  tests/e2e/specs/userprofile.js
Labels: bug
