Repository cylc/cylc-ui, pull requests merged in 2020-01, with the labels that each got.

#361 Remove the unloved footer component.
  CHANGES.md
  src/components/core/Footer.vue
  src/lang/en-GB/App.json
  src/lang/pt-BR/App.json
  src/layouts/Default.vue
  src/styles/cylc/_footer.scss
  src/styles/index.scss
Labels: Design

#368 Use a single WebSocket, and specify no-cache for the GraphQL links
  src/main.js
  src/services/workflow.service.js
  src/utils/graphql.js
Labels: bug

#371 Tweak workflows component sizes.
  src/styles/cylc/_workflow.scss
Labels: Design

#370 Workflows table tidy and hide
  CHANGES.md
  src/components/cylc/Drawer.vue
  src/lang/en-GB/Workflows.json
  src/lang/pt-BR/Workflows.json
  src/views/Dashboard.vue
  src/views/GScan.vue
Labels: Design

#360 drop IE support?
  public/index.html
Labels: question
