Repository cylc/cylc-ui, pull requests merged in 2021-11, with the labels that each got.

#806 Toolbar play from stopped
  src/components/cylc/workflow/Toolbar.vue
Labels: small

#841 actions: fix release stage one
  .github/workflows/create_release_pr.yml
Labels: infrastructure

#839 Improve style of Lumino tab close button
  src/styles/cylc/_workflow.scss
Labels: small

#845 GH Actions: update release workflows
  .github/workflows/auto_publish_release.yml
  .github/workflows/create_release_pr.yml
Labels: small, infrastructure

#847 update deps
  package.json
  yarn.lock
Labels: dependencies

#860 GH Actions: Simplify caching
  .github/workflows/main.yml
Labels: small, infrastructure
