Repository cylc/cylc-ui, pull requests merged in 2022-04, with the labels that each got.

#975 Fix .mailmap
  .github/workflows/shortlog.yml
  .mailmap
Labels: bug

#981 Test hierarchical gscan
  tests/unit/components/cylc/gscan/gscan.vue.spec.js
Labels: small

#982 aotf: support flow arguments
  src/components/graphqlFormGenerator/components/vuetify.js
  src/utils/aotf.js
Labels: small

#971 Update cypress
  package.json
  yarn.lock
Labels: dependencies, javascript
