Repository cylc/cylc-ui, pull requests merged in 2022-10, with the labels that each got.

#1115 Bump cypress to v10.10.0
  package.json
  yarn.lock
Labels: dependencies, javascript

#1122 Dashboard documentation links open in new tab
  .eslintrc.js
  src/views/Dashboard.vue
Labels: small

#1124 more items per page options in table view
  CHANGES.md
  src/components/cylc/table/Table.vue
Labels: small, UX/UI
