Repository cylc/cylc-ui, pull requests merged in 2022-01, with the labels that each got.

#873 Change development to host in Header
  CHANGES.md
  src/components/cylc/Header.vue
  tests/e2e/specs/header.js
Labels: small

#874 changes suggested by dependabot
  package.json
  yarn.lock
Labels: dependencies

#893 Dependencies
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies, javascript

#897 consolidiation on dependabot changes
  package.json
  yarn.lock
Labels: dependencies, javascript

#905 Consolidate Dependabot changes
  package.json
  yarn.lock
Labels: dependencies
