Repository cylc/cylc-ui, pull requests merged in 2022-05, with the labels that each got.

#999 aotf: fix mutations in workflow toolbar
  src/components/cylc/workflow/Toolbar.vue
  src/services/workflow.service.js
Labels: bug

#1000 Update deps 2
  docs/authentication/jwt/package-lock.json
  docs/authentication/jwt/package.json
  package.json
  tests/e2e/specs/graphiql.js
  yarn.lock
Labels: dependencies, javascript

#1008 Eslint: use `no-only-tests` in production only
  .github/workflows/main.yml
  src/services/mock/.eslintrc.js
  tests/.eslintrc.js
Labels: small, infrastructure

#1009 caniuselite
  yarn.lock
Labels: dependencies

#1021 Renovatebot labels; bring back Dependabot for GH Actions only
  .github/dependabot.yml
  .gitignore
  renovate.json
Labels: small, infrastructure

#1024 Remove unnecessary dev dependencies
  README.md
  package.json
  postcss.config.js
  yarn.lock
Labels: dependencies, javascript
