Repository cylc/cylc-ui, pull requests merged in 2022-06, with the labels that each got.

#1044 Remove dependency on eslint-plugin-node
  package.json
  yarn.lock
Labels: dependencies, javascript

#1048 Remove outdated authentication doc folder
  docs/authentication/README.md
  docs/authentication/jwt/index.js
  docs/authentication/jwt/jwt_strategy.js
  docs/authentication/jwt/package-lock.json
  docs/authentication/jwt/package.json
Labels: small

#1051 Change 'batch sys' to 'job runner'.
  src/components/cylc/tree/TreeItem.vue
  src/components/cylc/tree/nodes.js
Labels: bug, small

#1058 aotf: add help field for BroadcastSetting
  src/components/graphqlFormGenerator/components/BroadcastSetting.vue
Labels: small
