Repository cylc/cylc-ui, pull requests merged in 2022-07, with the labels that each got.

#1054 aotf: add icon for the clean mutation
  src/utils/aotf.js
Labels: small

#1059 markdown: swap vue-markdown for markdown-it
  package.json
  src/components/Markdown.vue
  src/components/graphqlFormGenerator/FormGenerator.vue
  src/components/graphqlFormGenerator/FormInput.vue
  src/styles/cylc/_tooltip.scss
  yarn.lock
Labels: small, dependencies, security, javascript

#1063 deps: bump transitive "got" dependency to v12
  package.json
  yarn.lock
Labels: dependencies, security, javascript

#1060 deps: bump transitive nth-check dependency
  yarn.lock
Labels: dependencies, security

#1064 deps: bump nanoid 3.1.20 => 3.3
  yarn.lock
Labels: dependencies, security

#1067 deps: bump selfsigned 1.10.14 => 2.0.1
  package.json
  yarn.lock
Labels: dependencies, security, javascript

#1069 Trim unused dependencies
  package.json
  yarn.lock
Labels: dependencies, javascript

#1068 deps: bump terser
  yarn.lock
Labels: dependencies, security, javascript

#1074 Trim unnecessary direct dependencies on babel proposals
  package.json
  yarn.lock
Labels: dependencies, javascript

#1081 Fix mailmap
  .mailmap
Labels: small, infrastructure
