Repository cylc/cylc-ui, pull requests merged in 2022-03, with the labels that each got.

#928 Add mutations to Gscan workflow icons.
  CHANGES.md
  src/components/cylc/cylcObject/plugin.js
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/gscan/WorkflowIcon.vue
  src/components/cylc/tree/TreeItem.vue
  src/layouts/Default.vue
  src/styles/cylc/_gscan.scss
  src/views/Workflow.vue
  tests/e2e/specs/gscan.js
  tests/e2e/specs/menu.js
Labels: enhancement

#978 Use eslint-plugin-no-only-tests
  package.json
  tests/.eslintrc.js
  tests/e2e/.eslintrc.js
  tests/e2e/specs/dashboard.js
  tests/e2e/specs/table.js
  yarn.lock
Labels: small, dependencies, javascript

#967 Improve display of workflow toolbar on narrow viewports
  src/components/cylc/Toolbar.vue
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/workflow/Toolbar.vue
  src/styles/cylc/_toolbar.scss
  src/styles/index.scss
Labels: bug
