Repository cylc/cylc-ui, pull requests merged in 2022-02, with the labels that each got.

#891 Show Cylc object ID, type and status at top of mutations menu
  CHANGES.md
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/cylcObject/plugin.js
  src/components/cylc/table/Table.vue
  src/components/cylc/tree/TreeItem.vue
  src/components/cylc/workflow/Toolbar.vue
  src/components/graphqlFormGenerator/FormGenerator.vue
  src/styles/cylc/_menu.scss
  src/styles/index.scss
  src/utils/aotf.js
  tests/e2e/specs/menu.js
  tests/unit/components/graphqlFormGenerator/formgenerator.vue.spec.js
Labels: enhancement, design

#906 made mobile burger button dark, hence actually visible
  src/components/cylc/Toolbar.vue
  src/components/cylc/workflow/Toolbar.vue
Labels: bug, small, accessibility

#911 Update dependencies
  package.json
  yarn.lock
Labels: dependencies, javascript

#912 Fixed mutations menu showing up more then once
  src/views/Table.vue
  src/views/Tree.vue
Labels: small

#917 Update dependencies
  package.json
  yarn.lock
Labels: dependencies, javascript

#927 Prevent mutation menu closing when clicking on another task or cycle
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/cylcObject/plugin.js
  src/styles/index.scss
  tests/e2e/specs/menu.js
  tests/e2e/specs/tree.js
Labels: bug

#931 Fix incorrect nesting of hierarchical dirs in GScan
  src/components/cylc/gscan/nodes.js
Labels: bug

#919 Focus the latest input box created when user clicks add button
  src/components/graphqlFormGenerator/components/List.vue
Labels: small

#943 Add useful unit tests opts to README
  README.md
  tests/unit/components/cylc/gscan/gscan.vue.spec.js
Labels: small

#926 Add codecov config
  .codecov.yml
  .github/workflows/main.yml
  README.md
Labels: small, infrastructure

#923 Update lumino
  package.json
  yarn.lock
Labels: dependencies, javascript

#948 Update dependencies
  package.json
  yarn.lock
Labels: dependencies, javascript
