Repository cylc/cylc-ui, pull requests merged in 2023-04, with the labels that each got.

#1249 Fix bug where subscriptions would not update on query change
  CHANGES.md
  src/components/cylc/workflow/index.js
  src/mixins/subscriptionComponent.js
  src/mixins/subscriptionView.js
  src/views/Dashboard.vue
  src/views/Graph.vue
  src/views/Guide.vue
  src/views/Log.vue
  src/views/Table.vue
  src/views/Tree.vue
  src/views/UserProfile.vue
  src/views/Workflows.vue
  src/views/WorkflowsTable.vue
  src/views/Workspace.vue
  tests/unit/components/cylc/drawer.vue.spec.js
  tests/unit/components/cylc/workflow/index.spec.js
  tests/unit/mixins/subscriptionComponent.spec.js
  tests/unit/mixins/subscriptionView.spec.js
Labels: bug

#1266 Minor tweaks to table header.
  src/components/cylc/table/Table.vue
  tests/e2e/specs/table.cy.js
Labels: small

#1287 Prepare release: 1.6.0 (again)
  package.json
Labels: release

#1288 Prepare release: 1.6.0 (3rd time's the charm)
  .github/workflows/auto_publish_release.yml
  package.json
Labels: release
