Repository cylc/cylc-ui, pull requests merged in 2023-01, with the labels that each got.

#1168 fix for jumping of expanded mutations menu.
  CHANGES.md
  src/components/cylc/cylcObject/Menu.vue
Labels: bug

#1181 GH Actions: use ubuntu-latest for e2e tests
  .github/workflows/main.yml
Labels: small, infrastructure

#1211 Update changelog
  CHANGES.md
Labels: small

#1212 Fix broken link
  src/views/Dashboard.vue
  src/views/WorkflowsTable.vue
  src/views/Workspace.vue
  tests/e2e/specs/dashboard.cy.js
  tests/e2e/specs/workflowsTable.cy.js
  tests/e2e/specs/workspace.cy.js
Labels: bug, small

#1216 deps: remove unnecessary babel-loader dev dep
  package.json
  yarn.lock
Labels: dependencies

#1218 Replace alert bar with snackbar
  src/components/core/Alert.vue
  src/components/cylc/Mutation.vue
  src/components/graphqlFormGenerator/EditRuntimeForm.vue
  src/graphql/index.js
  src/layouts/Default.vue
  src/model/Alert.model.js
  src/model/Subscription.model.js
  src/router/index.js
  src/services/workflow.service.js
  src/utils/aotf.js
  tests/e2e/specs/alert.cy.js
  tests/e2e/specs/editRuntimeForm.cy.js
  tests/e2e/specs/layout.cy.js
  tests/e2e/specs/mutation.cy.js
  tests/unit/mixins/subscription.spec.js
  tests/unit/model/alert.model.spec.js
  tests/unit/services/user.service.spec.js
  tests/unit/store/index.spec.js
Labels: UX/UI

#1182 Allow filtering by ID instead of only task name
  CHANGES.md
  src/components/cylc/TaskFilter.vue
  src/components/cylc/common/filter.js
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/table/Table.vue
  src/components/cylc/tree/Tree.vue
  tests/e2e/specs/table.cy.js
  tests/e2e/specs/tree.cy.js
  tests/unit/components/cylc/table/table.data.js
  tests/unit/components/cylc/table/table.vue.spec.js
Labels: bug, enhancement, UX/UI
