Repository cylc/cylc-ui, pull requests merged in 2023-10, with the labels that each got.

#1484 renovate: use analysis view label for apexcharts deps
  renovate.json
Labels: small, infrastructure

#1498 fix renovate config
  renovate.json
Labels: small, infrastructure

#1496 Bug overzealous timestamps
  src/components/cylc/log/Log.vue
Labels: small

#1434 Accessibility/appearance improvements
  CHANGES.md
  src/components/core/Alert.vue
  src/components/cylc/Job.vue
  src/components/cylc/table/Table.vue
  src/components/cylc/tree/TreeItem.vue
  src/components/graphqlFormGenerator/FormGenerator.vue
  tests/e2e/specs/alert.cy.js
  tests/e2e/specs/mutation.cy.js
  tests/unit/components/cylc/core/alert.vue.spec.js
Labels: small, accessibility, UX/UI

#1501 Graph node: nudge the task icons down
  src/components/cylc/GraphNode.vue
Labels: small

#1502 Fix toolbar toggle button color not changing
  CHANGES.md
  src/views/Graph.vue
  src/views/Log.vue
Labels: bug, small

#1490 Bug fix graphql 403
  src/services/workflow.service.js
Labels: bug

#1518 GH Actions: upload coverage to Codecov in separate job
  .github/workflows/main.yml
Labels: small, infrastructure

#1479 data store: wipe workflow data on reload.
  src/graphql/queries.js
  src/services/treeCallback.js
  src/services/workflow.service.js
  src/views/Dashboard.vue
  src/views/Graph.vue
  src/views/README.md
  src/views/SimpleTree.vue
  src/views/Table.vue
  src/views/Tree.vue
  src/views/Workflows.vue
  src/views/WorkflowsTable.vue
  tests/unit/services/workflow.service.spec.js
Labels: bug

#1513 fix a couple of possible errors
  CHANGES.md
  src/components/cylc/tree/TreeItem.vue
  src/components/cylc/tree/util.js
  src/store/workflows.module.js
Labels: bug

#1416 Auto-flatten single-child directories in GScan sidebar
  CHANGES.md
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/cylcObject/plugin.js
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/gscan/sort.js
  src/components/cylc/tree/GScanTreeItem.vue
  src/components/cylc/tree/JobDetails.vue
  src/components/cylc/tree/Tree.vue
  src/components/cylc/tree/TreeItem.vue
  src/services/mock/generate
  src/services/mock/json-server.js
  src/services/mock/json/index.cjs
  src/services/mock/json/workflows/multi.json
  src/services/mock/json/workflows/one.json
  src/services/mock/websockets.js
  src/styles/cylc/_gscan.scss
  src/styles/index.scss
  src/views/Tree.vue
  tests/e2e/specs/editRuntimeForm.cy.js
  tests/e2e/specs/graphiql.cy.js
  tests/e2e/specs/gscan.cy.js
  tests/e2e/specs/menu.cy.js
  tests/e2e/specs/mutation.cy.js
  tests/e2e/specs/tree.cy.js
  tests/e2e/specs/userprofile.cy.js
  tests/e2e/specs/workflowsTable.cy.js
  tests/e2e/specs/workflowservice.cy.js
  tests/unit/components/cylc/gscan/gscan.vue.spec.js
  tests/unit/components/cylc/gscan/sort.spec.js
  tests/unit/components/cylc/tree/tree.data.js
  tests/unit/components/cylc/tree/tree.vue.spec.js
  tests/unit/components/cylc/tree/treeitem.vue.spec.js
Labels: UX/UI

#1529 Properly log errors that are presented as alerts
  src/layouts/Default.vue
  src/model/Alert.model.js
  src/model/Subscription.model.js
  src/router/index.js
  src/services/workflow.service.js
  src/store/options.js
  src/utils/aotf.js
  tests/e2e/specs/alert.cy.js
  tests/e2e/specs/userprofile.cy.js
  tests/unit/mixins/subscription.spec.js
  tests/unit/model/alert.model.spec.js
  tests/unit/services/user.service.spec.js
  tests/unit/store/index.spec.js
Labels: small
