Repository cylc/cylc-ui, pull requests merged in 2023-08, with the labels that each got.

#1419 Renovate: reduce noise more
  renovate.json
Labels: small, infrastructure

#1418 Fix duplicate blank tab bug
  src/components/cylc/workflow/Lumino.vue
  tests/e2e/specs/graphiql.cy.js
Labels: bug, small

#1423 deps: semver
  yarn.lock
Labels: dependencies, security, javascript

#1427 extra log files: remove legacy
  src/services/mock/json/IntrospectionQuery.json
Labels: small

#1428 Feature mutation form sticky buttons
  CHANGES.md
  CONTRIBUTING.md
  src/components/cylc/Mutation.vue
  tests/e2e/specs/mutation.cy.js
Labels: UX/UI

#1446 aotf: ensure log mutation is listed when appropriate
  src/components/cylc/cylcObject/Menu.vue
  src/utils/aotf.js
  tests/e2e/specs/menu.cy.js
Labels: bug, small
