Repository cylc/cylc-ui, pull requests merged in 2023-09, with the labels that each got.

#1471 Fix changelog
  CHANGES.md
Labels: small

#1489 GraphNode: nude the cycle point down a little
  src/components/cylc/GraphNode.vue
Labels: small, UX/UI

#1488 yarn up
  package.json
  yarn.lock
Labels: dependencies, security, javascript
