Repository cylc/cylc-ui, pull requests merged in 2023-07, with the labels that each got.

#1371 Renovate: enable automerge for certain dev dependency groups
  package.json
  renovate.json
Labels: infrastructure

#1374 Renovate: use GitHub native automerge
  renovate.json
Labels: small, infrastructure

#1380 aotf: Make set-outputs a primary mutation for namespaces.
  src/utils/aotf.js
Labels: small, UX/UI

#1383 Fix font size reset bug
  src/App.vue
  tests/e2e/specs/userprofile.cy.js
Labels: bug, small

#1386 Renovate schedule & Cypress component coverage
  cypress.config.js
  cypress/support/component.js
  package.json
  renovate.json
Labels: small, infrastructure

#1389 Fix unnecessary reactive data
  src/components/Markdown.vue
  src/components/cylc/ConnectionStatus.vue
  src/components/cylc/Drawer.vue
  src/components/cylc/TaskFilter.vue
  src/components/cylc/Toolbar.vue
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/table/Table.vue
  src/components/cylc/tree/Tree.vue
  src/components/cylc/tree/TreeItem.vue
  src/components/cylc/workflow/Toolbar.vue
  src/components/graphqlFormGenerator/FormGenerator.vue
  src/components/graphqlFormGenerator/components/List.vue
  src/views/Analysis.vue
  src/views/Dashboard.vue
  src/views/Graph.vue
  src/views/Log.vue
  src/views/UserProfile.vue
  src/views/WorkflowsTable.vue
Labels: efficiency

#1392 Make mutations menu more compact
  src/components/cylc/cylcObject/Menu.vue
Labels: small, UX/UI

#1340 Fix family tasks discrepancy in tree view
  CHANGES.md
  src/components/cylc/table/Table.vue
  src/graphql/queries.js
  src/store/workflows.module.js
  tests/unit/store/workflows.spec.js
Labels: bug

#1391 Renovate: automerge Vite dependencies
  renovate.json
Labels: small, infrastructure
