Repository cylc/cylc-ui, pull requests merged in 2023-02, with the labels that each got.

#1226 aotf: prevent the "offset" field from being filled in
  src/utils/aotf.js
Labels: bug, small

#1231 deps: bump loader-utils
  yarn.lock
Labels: dependencies, security, javascript

#1233 deps: json5
  yarn.lock
Labels: dependencies, javascript

#1230 store: fix ancestor order
  CHANGES.md
  src/services/mock/json/App.json
  src/store/workflows.module.js
  tests/unit/store/workflows.spec.js
Labels: bug

#1245 auto-publish: pin node to v16
  .github/workflows/auto_publish_release.yml
  package.json
Labels: release

#1252 Remove local issue templates.
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: small

#1187 Improve GScan filter menu
  CHANGES.md
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/gscan/filters.js
  tests/e2e/specs/gscan.cy.js
Labels: UX/UI

#1250 Replace actions/create-release with our version
  .github/workflows/auto_publish_release.yml
Labels: small, infrastructure
