Repository cylc/cylc-ui, pull requests merged in 2024-03, with the labels that each got.

#1466 Added Gantt chart
  CHANGES.md
  cypress/component/ganttchart.cy.js
  src/components/cylc/gantt/GanttChart.vue
  src/components/cylc/gantt/filter.js
  src/router/paths.js
  src/services/mock/json/ganttQuery.json
  src/services/mock/json/index.cjs
  src/views/Gantt.vue
  src/views/views.js
  tests/e2e/specs/gantt.cy.js
  tests/unit/components/cylc/analysis/filter.spec.js
  tests/unit/components/cylc/gantt/filter.spec.js
  tests/unit/components/cylc/gantt/ganttChart.vue.spec.js
  tests/unit/views/gantt.vue.spec.js
Labels: analysis view

#1688 Log view: use `initialOptions` to save & restore view state on navigation
  src/components/cylc/common/filter.js
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/workflow/Lumino.vue
  src/components/graphqlFormGenerator/EditRuntimeForm.vue
  src/utils/initialOptions.js
  src/utils/uid.js
  src/views/Log.vue
  tests/e2e/specs/log.cy.js
  tests/unit/components/cylc/common/filter.spec.js
  tests/unit/components/cylc/tree/tree.data.js
  tests/unit/utils/initialOptions.spec.js
  tests/unit/utils/uid.spec.js
  tests/unit/views/log.vue.spec.js
Labels: UX/UI

#1707 Remove no-longer-needed Vuetify workaround
  src/components/graphqlFormGenerator/EditRuntimeForm.vue
Labels: small

#1697 Fix yarn warnings about `react`
  package.json
  src/views/GraphiQL.vue
  yarn.lock
Labels: dependencies, javascript

#1718 GH Actions: add timeouts
  .github/workflows/main.yml
Labels: small, infrastructure

#1597 Added an icon for set
  src/utils/aotf.js
Labels: small
