Repository cylc/cylc-ui, pull requests merged in 2024-05, with the labels that each got.

#1773 Switch to `lodash-es` for treeshaking
  package.json
  vite.config.js
  yarn.lock
Labels: dependencies, javascript

#1778 Include XSRF token in userprofile request
  CONTRIBUTING.md
  changes.d/1778.fix
  src/graphql/graphiql.js
  src/graphql/index.js
  src/services/user.service.js
  src/utils/urls.js
Labels: bug

#1758 Ensure clicking "Log" in command menu works for workflows in GScan sidebar
  changes.d/1758.fix.md
  package.json
  src/components/cylc/cylcObject/Menu.vue
  src/utils/aotf.js
  tests/e2e/specs/log.cy.js
Labels: bug, small

#1780 graph: fix graph rendering
  cypress/component/cylc-graph-node.cy.js
  cypress/component/cylc-icons.cy.js
  src/components/cylc/GraphNode.vue
  src/components/cylc/SVGTask.vue
  src/components/cylc/cylcObject/Menu.vue
  src/styles/index.scss
  src/views/Graph.vue
Labels: bug

#1797 Add missing changelog entry
  changes.d/1780.fix.md
Labels: small

#1795 GH Actions: print draft changelog job summary
  .github/workflows/main.yml
Labels: small, infrastructure

#1798 Address warnings emitted during unit tests & tidy
  src/components/cylc/gantt/GanttChart.vue
  tests/unit/components/cylc/analysis/analysistimeseries.vue.spec.js
  tests/unit/components/cylc/gantt/ganttChart.vue.spec.js
  tests/unit/components/cylc/workflow/toolbar.vue.spec.js
Labels: small

#1706 Gantt view: colour code by cycle point
  changes.d/1466.feat.md
  src/components/cylc/gantt/GanttChart.vue
Labels: data workflows team

#1805 Tests: fix mocking of apollo client
  tests/unit/services/workflow.service.spec.js
Labels: small
