Repository cylc/cylc-ui, pull requests merged in 2024-04, with the labels that each got.

#1729 TableView: Use initialOptions prop to save view state (cherry-pick #1711)
  CHANGES.md
  src/components/cylc/table/Table.vue
  src/views/Table.vue
  src/views/Tree.vue
  tests/e2e/specs/table.cy.js
  tests/unit/components/cylc/table/table.vue.spec.js
  tests/unit/views/table.vue.spec.js
Labels: sync

#1736 2.4.x -> master
  CHANGES.md
  package.json
Labels: sync

#1751 Table view: remember sort & pagination state on navigation
  CHANGES.md
  src/components/cylc/table/Table.vue
  src/views/Table.vue
  tests/e2e/specs/table.cy.js
Labels: small, UX/UI

#1760 Switch to towncrier for changelog
  .github/workflows/create_release_pr.yml
  .github/workflows/main.yml
  CHANGES.md
  CONTRIBUTING.md
  changes.d/1751.feat.md
  changes.d/template.jinja
  pyproject.toml
Labels: infrastructure

#1745 Gantt view: use `initialOptions` to save & restore view state on navigation
  changes.d/1745.feat.md
  src/views/Gantt.vue
  tests/e2e/specs/gantt.cy.js
Labels: small, UX/UI, data workflows team

#1510 Add job timings vs cycle point visualisation
  src/components/cylc/analysis/TimeSeries.vue
  src/components/cylc/gantt/GanttChart.vue
  src/services/mock/json/analysisQuery.json
  src/services/mock/json/index.cjs
  src/styles/index.scss
  src/views/Analysis.vue
  tests/e2e/specs/analysis.cy.js
  tests/unit/components/cylc/analysis/analysistable.vue.spec.js
  tests/unit/components/cylc/analysis/analysistimeseries.vue.spec.js
Labels: data workflows team

#1771 Renovate: address warning
  renovate.json
Labels: small, infrastructure

#1772 Add missed changelog entry
  changes.d/1510.feat.md
Labels: small
