Repository cylc/cylc-ui, pull requests merged in 2024-08, with the labels that each got.

#1888 Increase width of Edit Runtime dialog
  changes.d/1888.feat.md
  src/components/cylc/commandMenu/Menu.vue
  src/components/graphqlFormGenerator/components/MapItem.vue
  src/utils/aotf.js
Labels: small, UX/UI

#1904 yarn up
  yarn.lock
Labels: dependencies, javascript

#1889 Towncrier: enable checking of fragment names
  pyproject.toml
Labels: small, infrastructure

#1907 Fix janky 404 page
  src/views/NoAuth.vue
  src/views/NotFound.vue
Labels: small
