Repository cylc/cylc-ui, pull requests merged in 2024-01, with the labels that each got.

#1623 store: more efficient family tree building
  src/store/workflows.module.js
Labels: efficiency

#1631 data store: remove redundant safety check
  src/store/workflows.module.js
Labels: small, efficiency

#1633 GH Actions: fix screenshots artifact name clash
  .github/workflows/main.yml
Labels: small, infrastructure

#1643 Fix arrow keys not working in Edit Runtime form inputs
  CHANGES.md
  src/components/graphqlFormGenerator/EditRuntimeForm.vue
Labels: bug, small

#1619 tree: more efficient expand/collapse buttons
  CHANGES.md
  src/components/cylc/tree/GScanTreeItem.vue
  src/components/cylc/tree/JobDetails.vue
  src/components/cylc/tree/Tree.vue
  src/components/cylc/tree/TreeItem.vue
  src/components/cylc/tree/util.js
  src/styles/cylc/_gscan.scss
  src/styles/cylc/_tree.scss
  tests/e2e/specs/gscan.cy.js
  tests/e2e/specs/mutation.cy.js
  tests/e2e/specs/tree.cy.js
Labels: small, efficiency

#1642 Update Vuetify to 3.5.1
  README.md
  package.json
  src/App.vue
  src/components/core/Alert.vue
  src/components/cylc/Mutation.vue
  src/components/cylc/TaskFilterSelect.vue
  src/components/cylc/analysis/AnalysisTable.vue
  src/components/cylc/cylcObject/Menu.vue
  src/components/cylc/gscan/GScan.vue
  src/components/cylc/table/Table.vue
  src/components/cylc/tree/util.js
  src/components/graphqlFormGenerator/EditRuntimeForm.vue
  src/components/graphqlFormGenerator/components/vuetify.js
  src/main.js
  src/mixins/appSettings.js
  src/plugins/vuetify.js
  src/styles/cylc/_gscan.scss
  src/styles/cylc/_table.scss
  src/styles/cylc/_tree.scss
  src/styles/index.scss
  src/styles/settings.scss
  src/views/Dashboard.vue
  src/views/Log.vue
  src/views/UserProfile.vue
  src/views/WorkflowsTable.vue
  tests/e2e/specs/log.cy.js
  tests/e2e/specs/mutation.cy.js
  tests/unit/components/app.vue.spec.js
  tests/unit/components/cylc/analysis/analysistable.vue.spec.js
  tests/unit/components/cylc/table/table.vue.spec.js
  tests/unit/utils/toolbar.spec.js
  yarn.lock
Labels: dependencies, javascript
