Repository cylc/cylc-ui, pull requests merged in 2024-11, with the labels that each got.

#1979 toolbar: disable n-window selector if appropriate
  changes.d/1979.fix.md
  src/components/cylc/workspace/Toolbar.vue
Labels: small

#1974 task state filters: add select all action
  changes.d/1974.feat.md
  src/components/cylc/TaskFilterSelect.vue
  tests/e2e/specs/tree.cy.js
Labels: small, UX/UI

#1982 jupyter lab dashboard link
  changes.d/1982.feat.md
  package.json
  src/model/User.model.js
  src/utils/icons.js
  src/views/Dashboard.vue
  src/views/UserProfile.vue
  tests/e2e/specs/dashboard.cy.js
  yarn.lock
Labels: small

#1994 move GraphiQL from the draw to the dashboard
  src/components/cylc/Drawer.vue
  src/views/Dashboard.vue
Labels: small

#2006 Renovate: fix config for sass
  renovate.json
Labels: small, infrastructure
