Repository cylc/cylc-ui, pull requests merged in 2025-06, with the labels that each got.

#2175 Add workflow Cylc version to toolbar and menu
  src/components/cylc/commandMenu/Menu.vue
  src/components/cylc/workspace/Toolbar.vue
  src/services/mock/json/workflows/multi.json
  src/services/mock/json/workflows/one.json
Labels: small

#2206 Graph view: Fix missing edge between collapsed cycles that contain collapsed families
  src/views/Graph.vue
Labels: bug, small

#2091 backend graphql-core v3 adjustments
  src/utils/aotf.js
Labels: small

#2204 Workspace layouts: avoid duplicate layout saving when resetting to default
  src/components/cylc/workspace/Lumino.vue
  src/utils/reactivity.js
  tests/unit/utils/reactivity.spec.js
Labels: small

#2214 Update `yarn.lock`
  yarn.lock
Labels: small, dependencies, javascript
